# Generated by Django 4.1.7 on 2023-02-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fc_club',
            new_name='FcClub',
        ),
    ]
